# Generated by Django 5.0.4 on 2024-04-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reserva_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='numero_de_musicos',
            new_name='capacidad',
        ),
    ]
