# Generated by Django 5.0.4 on 2024-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_grupo_tipo_alter_tipo_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('instrumental', 'Instrumental'), ('con voz', 'Con Voz')], default='instrumental', max_length=20),
        ),
    ]
