# Generated by Django 5.0.4 on 2024-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_delete_tipo_alter_grupo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('instrumental', 'Instrumental'), ('convoz', 'Con Voz')], default='instrumental', max_length=20),
        ),
    ]
