# Generated by Django 5.0.4 on 2024-04-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_grupo_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='size',
            field=models.CharField(choices=[('duo', 'Duo'), ('trio', 'Trio'), ('cuarteto', 'Cuarteto'), ('combo', 'Combo')], default='combo', max_length=20),
        ),
    ]
